# Lightning - macOS Application Launcher

default:
    @just --list

# Generate BuildInfo.swift with the current git commit hash
_build-info:
    @echo '// Auto-generated by `just build` — do not edit manually.' > Sources/Lightning/BuildInfo.swift
    @echo 'enum BuildInfo {' >> Sources/Lightning/BuildInfo.swift
    @echo '    static let gitCommit = "'"$(git rev-parse --short HEAD)"'"' >> Sources/Lightning/BuildInfo.swift
    @echo '}' >> Sources/Lightning/BuildInfo.swift

# Build in debug mode
build: _build-info
    swift build

# Build in release mode
release: _build-info
    swift build -c release

# Run the app in debug mode
run: _build-info
    swift build && .build/debug/Lightning

# Run tests
test:
    swift test

# Clean build artifacts
clean:
    swift package clean
    rm -f Sources/Lightning/BuildInfo.swift
    rm -rf .build

# Create Lightning.app bundle from release build
bundle: _build-info
    bash Scripts/bundle.sh

# Resolve package dependencies
resolve:
    swift package resolve
